// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// IFM_margin_obj_cpp
double IFM_margin_obj_cpp(NumericVector pars, NumericVector data_p, NumericVector z_values, std::string family);
RcppExport SEXP _vineclust_IFM_margin_obj_cpp(SEXP parsSEXP, SEXP data_pSEXP, SEXP z_valuesSEXP, SEXP familySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type data_p(data_pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z_values(z_valuesSEXP);
    Rcpp::traits::input_parameter< std::string >::type family(familySEXP);
    rcpp_result_gen = Rcpp::wrap(IFM_margin_obj_cpp(pars, data_p, z_values, family));
    return rcpp_result_gen;
END_RCPP
}
// eval_margin_cpp
NumericVector eval_margin_cpp(NumericVector data_p, std::string family, NumericVector pars, std::string type);
RcppExport SEXP _vineclust_eval_margin_cpp(SEXP data_pSEXP, SEXP familySEXP, SEXP parsSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type data_p(data_pSEXP);
    Rcpp::traits::input_parameter< std::string >::type family(familySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(eval_margin_cpp(data_p, family, pars, type));
    return rcpp_result_gen;
END_RCPP
}
// eval_all_margins_cpp
NumericMatrix eval_all_margins_cpp(NumericMatrix data, CharacterVector families, NumericMatrix params, std::string type);
RcppExport SEXP _vineclust_eval_all_margins_cpp(SEXP dataSEXP, SEXP familiesSEXP, SEXP paramsSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type families(familiesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(eval_all_margins_cpp(data, families, params, type));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_vineclust_IFM_margin_obj_cpp", (DL_FUNC) &_vineclust_IFM_margin_obj_cpp, 4},
    {"_vineclust_eval_margin_cpp", (DL_FUNC) &_vineclust_eval_margin_cpp, 4},
    {"_vineclust_eval_all_margins_cpp", (DL_FUNC) &_vineclust_eval_all_margins_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_vineclust(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
