# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IFM_margin_obj_cpp <- function(pars, data_p, z_values, family) {
    .Call(`_vineclust_IFM_margin_obj_cpp`, pars, data_p, z_values, family)
}

eval_margin_cpp <- function(data_p, family, pars, type) {
    .Call(`_vineclust_eval_margin_cpp`, data_p, family, pars, type)
}

eval_all_margins_cpp <- function(data, families, params, type) {
    .Call(`_vineclust_eval_all_margins_cpp`, data, families, params, type)
}

